project:
  type: website
  output-dir: docs

website:
  title: "Louis Chua"
  favicon: /logo.png
  navbar:
    tools:
      - icon: github
        href: https://github.com/showandgo
      - icon: twitter
        href: https://twitter.com/sirensorts
      - icon: vector-pen
        href: https://sirensorts.substack.com/?utm_source=substack&utm_medium=web&utm_campaign=substack_profile
    background: light
    foreground: dark
    search: false
    logo: /logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: prj.qmd
        text: News
      - href: art.qmd
        text: Artwork
  page-footer: 
    center: "Copyright 2023, Louis Chua"

format:
  html:
    theme: sandstone
    #theme: 
     # - mystyles.scss
    #mainfont: Nunito
    css: styles.css
    toc: true

editor: visual

